### PR TITLE
Groups pages

### PR DESCRIPTION
**Pull request by apratan**
Screens where a User can view their groups and create new groups. The frontend is connected to the backend

### CODE REVIEW

**Comment by apratan** [comment]
> What is the attribute stuff in the user model?

I was just using it for testing and forgot to remove it. I've pushed a new commit with 'stuff' removed

**Comment by bfok123** [comment]
I merged this with the navigation branch so that the Groups screen is accessible from the bottom nav bar. Also linked the Create Groups page with the Groups page as well. 

Most of it looks good, only thing I have to mention is that you should try not to use 'px' values for margins, height, width, etc. because that won't be a responsive layout. I also tried running it on my Android device and the 'px' values gave me an error (even though it works on web). If you could change those values to percentage values to make it responsive and work on mobile devices that would be great. I know it's kind of annoying to make the change, but shouldn't take too long.

**Comment by milannair** [comment]
What is the package-lock.json in the root directory for?

**Comment by apratan** [comment]
> What is the package-lock.json in the root directory for?

That's where it's always been for me. I don't think I moved this file around at all. Where should it ideally be?

**Pull request merged**
